name: Go CI

on:
  push:
    branches:
      - main
      - 'feature/*' # Trigger on pushes to any feature branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...
