name: Go CI

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Run linter
        run: |
          go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          golangci-lint run ./...

      - name: Run tests
        run: go test -v ./...

