name: Go CI

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install golangci-lint
        run: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

      - name: Run linting
        run: make lint

      - name: Run tests
        run: make test
